### PR TITLE
fixed footer issue

### PR DESCRIPTION
**Pull request by DineshKoushik**
# Description
I have set the position of footer to the bottom of page

issue: #3

### CODE REVIEW

**Review by himanshu007-creator — CHANGES_REQUESTED** [review]
Nice work, but now the div <code>pricing detail</code> Seems completely touched to footer, please insert a <code>BR</code> tag or bottom margin to make so me space.

**Comment by DineshKoushik** [comment]
@himanshu007-creator , are they? I actually gave margin-top to the footer. They weren't touching in my local.

**Comment by himanshu007-creator** [comment]
See here, if you download anything then the behavior of footer changes, it should not

**Comment by DineshKoushik** [comment]
@himanshu007-creator , yeah I got it. But margin-bottom is not working for this case. What would be the solution?

**Pull request closed without merging**
